config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/index' => 'home#index'

  #Projet Blog
  resources :articles do
    resources :comments
  end 
  mount Ckeditor::Engine => '/ckeditor'


  #Projet Réservation-Intervenants
  get '/intervenants' => 'calendrier#show'
  get '/intervenants/reservation/:day-:month' => 'calendrier#reservation'
  post '/intervenants/reservation' => 'calendrier#create'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :day, :month, :year,:content, presence: true
	validates :title, presence: true,
					length: { minimum: 12, too_short: ": Votre titre est trop court"}
	validates :subtitle, presence: true,
					length: { minimum: 12, too_short: "Votre sous-titre est trop court" }
end

app/models/calendrier.rb
class Calendrier < ActiveRecord::Base
	validates :nom, presence: true
 	validates :prenom, presence: true
 	validates :email, presence: true
 	validates :telephone, presence: true
  	validates :date, presence: true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
   	@articles = Article.all
  end
	
  def new
    @article = Article.new
	end
	
  def create
		@article = Article.new(article_params)
    if @article.save
      redirect_to articles_path, notice: "L'article a été créé"
    else
      redirect_to new_article_path
    end
	end
	
  def show
		@article = Article.find(params[:id])
	end
	
  def edit
  	@article = Article.find(params[:id])
  end
	
  def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
  		redirect_to @article
		else
  		render 'edit'
		end
	end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

 	private
	
  def article_params
  	params.require(:article).permit(:day, :month, :year, :title, :subtitle, :content)
	end
end

app/controllers/calendrier_controller.rb
class CalendrierController < ApplicationController
	def show
		@intervenant = Calendrier.all.order("date")
		@month = {"06"=>["Juin", "June", 30, 1], "07"=>["Juillet", "July", 31, 3], "08"=>["Août", "August", 31, 6], "09"=>["Septembre", "September", 30, 2], "10"=>["Octobre", "October", 31, 4]}
		@day = ["Lundi", "Mardi", "Mercredi" , "Jeudi", "Vendredi", "Samedi", "Dimanche"]
	end

	def reservation
		@date = "2015-#{params[:month]}-#{params[:day]}"
	end

	def create
		params[:description] = params[:description].gsub(/[<>]/, '')
		params[:resa]["description"] = params[:description]
		@intervenant = Calendrier.new(reservation_params)
		@intervenant.save
		redirect_to intervenants_path
	end

	private
	  def reservation_params
	    params.require(:resa).permit(:nom, :prenom, :email, :telephone, :date, :description)
	  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end
  
	private
	def comment_params
		params.require(:comment).permit(:name, :body)
	end		
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/calendrier_helper.rb
module CalendrierHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/edit.html.erb
<div class="form">
	<h1>Editer l'article</h1>
	<div class="formulaire">
		<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
			<% if @article.errors.any? %>
			    <div id="error_explanation">
			        <%= pluralize(@article.errors.count, "erreur") %> : Impossible de sauvegarder l'article, veuillez remplir tous les champs
			        <ul>
						<% @article.errors.full_messages.each do |msg| %>
          				<li><%= msg %></li>
       				 <% end %>
       				</ul> 
			    </div>
		  <% end %>
		  <p class="selecteur">
		    <%= f.label :jour %>
		    <%= f.select :day, (1..31).to_a %>
		    <%= f.label :mois %>
		    <%= f.select :month, ["janv", "févr", "mars", "avr", "mai", "juin", "juil", "août", "sept", "oct", "nov", "déc"] %>
		    <%= f.label :année %>
		    <%= f.select :year, ["2015", "2016", "2017"] %>
		  </p> 
		  <p>
		    <%= f.label :titre %><br>
		    <%= f.text_area :title, :class => "text_field" %>
		  </p>
		  <p>
		    <%= f.label :"sous-titre" %><br>
		    <%= f.text_area :subtitle, :class => "text_field" %>
		  </p>
		  <p>
		    <%= f.label :texte %><br>
		    <%= f.cktext_area :content %>
		  </p>
		 
		  <p>
		    <%= f.submit 'Enregistrer les modifications' %>
		  </p>
		<% end %>
	</div>
</div>

app/views/articles/index.html.erb
<div class="visual">
  <img src="/assets/fondmaster.png" alt="fondmaster" />
</div>
<div class="bandeau">
  <div class="logocinema">
    <img src="/assets/bannierefestivalcinemablanc.svg" class="img-responsive" width="100%" alt="logofest" title="logofest" />
  </div>
</div>
  <div class="label">
    <%= flash[:notice] %>
  </div>
<div class="nav_blog">
  <ul>
    <li><%= link_to "nouvel article", new_article_path %></li>
    <li><a href="http://festivalducinemalibre.com" target="_blank">fcl</a></li>
  </ul>
</div>
<article class="container_blog">
  <div class="catch">
      <div class="catchnumber">3ème édition
      </div>
      <div class="catchplace">HAMBOURG
      </div>
      <div class="catchdate">28-30 Août 2015
      </div>
    </div>
  <% @articles.reverse.each do |article| %>
    <div class="article">
      <div class="info_blog">
        <div class="day">
            <%= article.day %>
        </div>
        <div class="date_blog">
          <div class="month">
              <%= article.month %>
          </div>
           <div class="year">
              <%= article.year %>
          </div>
        </div>             
        <h1 class="title">
          <%= article.title %>
        </h1>
      </div> 
      <h3 class="subtitle">
        <%= article.subtitle %>
      </h3>
      <div class="content">
        <%= article.content.html_safe %>
      </div>
      <div class="button">
        <%= link_to (image_tag('croix.svg')),article_path(article) %>
      </div>
    </div>
  <% end %>
</article>

app/views/articles/new.html.erb
<div class="form">
	<h1>Nouvel article</h1>
	  <% if @article.errors.any? %>
      <div id="error_explanation">
        <%= pluralize(@article.errors.count, "erreur") %> : Impossible de sauvegarder l'article, veuillez remplir tous les champs.
      	<ul>
    			<% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
     		</ul> 
      </div>
  <% end %>
	<%= form_for :article, url: articles_path  do |f| %>
    <p class="selecteur">
    <%= f.label :"jour" %>
    <%= f.select :day, (1..31).to_a %>
    <%= f.label :mois %>
    <%= f.select :month, ["janv", "févr", "mars", "avr", "mai", "juin", "juil", "août", "sept", "oct", "nov", "déc"] %>
    <%= f.label :année %>
    <%= f.select :year, ["2015", "2016", "2017"] %>
    </p> 
    <p>
    <%= f.label :titre %><br>
    <%= f.text_area :title, :class => "text_field" %>
    </p>
    <p>
    <%= f.label :"sous-titre" %><br>
    <%= f.text_area :subtitle, :class => "text_field" %>
    </p>
    <p>
    <%= f.label :texte %><br>
    <%= f.cktext_area :content %>
    </p>
    <%= f.submit 'Enregistrer le nouvel article', class: "submit_btn" %>
	<% end %>
</div>

app/views/articles/show.html.erb
<div class="article">
	<div class='info_blog'>
		<div class="day">
      	 <%= @article.day %>
     	</div>
    	<div class='date_blog'>
   			<div class="month">
       			<%= @article.month %>
     		</div>
    		<div class="year">
       			<%= @article.year %>
    		</div>
    	</div>            
		<p class="title">
	 		<%= @article.title %>
		</p>
	</div>	 
	<p class="subtitle">
	  <%= @article.subtitle %>
	</p>
	<div class="content">
	  <%= @article.content.html_safe %>
	</div>
	<div class="comment_form">
	<h5>Ajouter un commentaire : </h5>
		<%= form_for ([@article, @article.comments.build]) do |f| %>
			<p>
			    <%= f.label :nom %><br>
			    <%= f.text_field :name %>
			</p>
			<p>
			    <%= f.label :commentaire %><br>
			    <%= f.text_area :body, :class => "text_field" %>
			</p>
			<%= f.submit 'Envoyer le commentaire', class: "submit_btn" %>
		<% end %>
	</div>
	<table class="comment_list">	 
		<th>Commentaires</th>
		<tr>
			<td>Nom</td>
			<td>Commentaires</td>
		</tr>
		<% @article.comments.each do |comment| %>
			<tr>
				<td class="nom_blog"><%= comment.name %></td>
				<td ><%= comment.body %></td>
			</tr>
		<% end %>
	</table>	
    <%= link_to (image_tag('home.png')), articles_path, :class => "home" %>
    <div class='icon_blog'>
		<%= link_to (image_tag('edit.png')), edit_article_path(@article) %>
		<%= link_to (image_tag('delete.png')), article_path(@article),
	              method: :delete,
	              data: { confirm: 'Etes-vous sûr ?' } %>
	</div>              
</div>

app/views/calendrier/reservation.erb
<div class="container-fluid resa-background">

	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<h1 class="resa-titre text-center">Formulaire Intervenant</h1>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<form method="post" action="/intervenants/reservation" id="form_resa">
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 input--resa">
					<input type="text" class="input__field input__field--resa" name="resa[nom]" autocomplete="off">
					<label class="input__label input__label--resa">
						<span class="input__label-content input__label-content--resa">Nom</span>
					</label>
					<svg class="graphic graphic--resa" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
						<path d="M0,58.0c0,0,298.666,0,399.333,0C448.336,56.5,513.994,46,597,46c77.327,0,135,10.5,200.999,10.5c95.996,0,402.001,0,402.001,0"/>
						<path d="M0,2.5c0,0,298.666,0,399.333,0C448.336,2.5,513.994,13,597,13c77.327,0,135-10.5,200.999-10.5c95.996,0,402.001,0,402.001,0"/>
					</svg>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 input--resa">
					<input type="text" class="input__field input__field--resa" name="resa[prenom]" autocomplete="off">
					<label class="input__label input__label--resa">
						<span class="input__label-content input__label-content--resa">Prénom</span>
					</label>
					<svg class="graphic graphic--resa" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
						<path d="M0,58.0c0,0,298.666,0,399.333,0C448.336,56.5,513.994,46,597,46c77.327,0,135,10.5,200.999,10.5c95.996,0,402.001,0,402.001,0"/>
						<path d="M0,2.5c0,0,298.666,0,399.333,0C448.336,2.5,513.994,13,597,13c77.327,0,135-10.5,200.999-10.5c95.996,0,402.001,0,402.001,0"/>
					</svg>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 input--resa">
					<input type="text" class="input__field input__field--resa" name="resa[email]" autocomplete="off">
					<label class="input__label input__label--resa">
						<span class="input__label-content input__label-content--resa">E-mail</span>
					</label>
					<svg class="graphic graphic--resa" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
						<path d="M0,58.0c0,0,298.666,0,399.333,0C448.336,56.5,513.994,46,597,46c77.327,0,135,10.5,200.999,10.5c95.996,0,402.001,0,402.001,0"/>
						<path d="M0,2.5c0,0,298.666,0,399.333,0C448.336,2.5,513.994,13,597,13c77.327,0,135-10.5,200.999-10.5c95.996,0,402.001,0,402.001,0"/>
					</svg>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 input--resa">
					<input type="text" class="input__field input__field--resa" name="resa[telephone]" autocomplete="off">
					<label class="input__label input__label--resa">
						<span class="input__label-content input__label-content--resa">Téléphone</span>
					</label>
					<svg class="graphic graphic--resa" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
						<path d="M0,58.0c0,0,298.666,0,399.333,0C448.336,56.5,513.994,46,597,46c77.327,0,135,10.5,200.999,10.5c95.996,0,402.001,0,402.001,0"/>
						<path d="M0,2.5c0,0,298.666,0,399.333,0C448.336,2.5,513.994,13,597,13c77.327,0,135-10.5,200.999-10.5c95.996,0,402.001,0,402.001,0"/>
					</svg>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 input--resa">
					<input readonly type="date" class="input__field input__field--resa date" name="resa[date]" value="<%= @date %>" autocomplete="off">
					<label class="input__label input__label--resa">
						<span class="input__label-content input__label-content--resa">Date Réservée</span>
					</label>
					<svg class="graphic graphic--resa" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
						<path d="M0,58.0c0,0,298.666,0,399.333,0C448.336,56.5,513.994,46,597,46c77.327,0,135,10.5,200.999,10.5c95.996,0,402.001,0,402.001,0"/>
						<path d="M0,2.5c0,0,298.666,0,399.333,0C448.336,2.5,513.994,13,597,13c77.327,0,135-10.5,200.999-10.5c95.996,0,402.001,0,402.001,0"/>
					</svg>
				</div>
			</div>
			<div class="row space-textarea">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 input--resa">
					<textarea class="textarea" name="description"></textarea>
					<label class="textarea__label textarea__label--resa">
						<span class="textarea__label-content textarea__label-content--resa">Domaine d'activité</span>
					</label>
					<svg class="graphic graphic2--resa" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
						<path d="M0,56.5c0,0,298.666,0,399.333,0C448.336,56.5,513.994,46,597,46c77.327,0,135,10.5,200.999,10.5c95.996,0,402.001,0,402.001,0"/>
						<path d="M0,1.5c0,0,298.666,0,399.333,0C448.336,2.5,513.994,13,597,13c77.327,0,135-10.5,200.999-10.5c95.996,0,402.001,0,402.001,0"/>
					</svg>
				</div>
			</div>
			<div class="form-button">
				<a class="resa-btn-cancel" href="/intervenants">Annuler</a>
				<a class="resa-btn-valid" id="resa-submit" onclick="document.getElementById('form_resa').submit(); document.getElementById('resa-submit').removeAttribute('onclick');">Valider</a>
			</div>
		</form>
	</div>
</div>

app/views/calendrier/show.erb
<div class="resa-background"></div>
<div class="resa-container">
<h1 class="resa-titre text-center">Réservez la date de votre intervention à Simplon.VE</h1>
  <% @month.each do |key,list| %>
    <div class="row">  
          
      <div class="resa-nom_mois">
        <%= list[0] %>
      </div>
      
      <div class="resa-calendrier">
        <div class="resa-mois">
    
          <% a = 1; b = 1; c = 1 %>

          <div class="resa-nom_jour">
            <% @day.each do |day| %>
              <div class="resa-jour">
                <%= day %>
              </div>
            <% end %>
          </div>

          <% while a < list[3] %>
            <% if b == 1 %>
              <div class="resa-semaine">
            <% end %>
            <div class="resa-jour">
            </div>
            <% a += 1; b += 1 %>
          <% end %>

      
          <% while c <= list[2] %>
            
            <% if b == 1 || b % 7 == 1 %>
              <div class="resa-semaine">
            <% end %>
        
            <% l = sprintf '%02d', c %>
            <% @date = [] %>
            <% @intervenant.each do |idate| %>
                <% @date << idate.date.strftime("%d-%m") %>
            <% end %>
            
            <% if @date.include?("#{l}-#{key}") %>
                <div class="resa-jour resa-indispo">
                  <%= c %>
                </div>
            <% elsif key == "08" && c < 17 %>
                <div class="resa-jour resa-weekend">
                  <%= c %>
                </div>
            <% elsif b % 7 == 6 %>
                <div class="resa-jour resa-weekend">
                  <a href="/intervenants/reservation/<%= l %>-<%= key %>">
                    <%= c %>
                  </a>
                </div>
            <% elsif b % 7 == 0 %>
                 <div class="resa-jour resa-weekend">
                  <%= c %>
                </div>
            <% else %>
              <div class="resa-jour resa-dispo">
                <a href="/intervenants/reservation/<%= l %>-<%= key %>">
                  <%= c %>
                </a>
              </div>
            <% end %>
            
            <% if b % 7 == 0 %>
              </div>
            <% end %>
            
            <% b += 1; c += 1 %>
          
          <% end %>

          <% while b % 7 != 1 %>
            <div class="resa-jour">
              
            </div>
            <% b += 1 %>
          <% end %>
    
          </div>
        </div>
      </div>

      <div class="resa-texte">
        <% @intervenant.each do |i| %>
          <% if i.date.strftime("%B") == list[1] %>
            <div class="resa-info">
              <div class="resa-date">
                <%= i.date.strftime("%e %B %Y").gsub(list[1], list[0]) %>: 
              </div>
              <div class="resa-nom">
                <%= i.nom %>
                <%= i.prenom %>
              </div>
              <div class="resa-contact">
                Email: <%= i.email %>, 
                Tel: <%= i.telephone %>
              </div>
              <div class="resa-desc">
                <%= i.description %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<img class="img" src="images/logoSimplonVE.jpg" alt="SimplonVE Logo">

<p>La fabrique sociale de développeurs(euses) Ardéchoise</p>

app/views/layouts/_footer.html.erb
<div id="footer">
	<h1>je suis un footer </h1>
	
<div class="reseaux_sociaux">
  <a href="https://twitter.com/simplonve" target="_blank"><img src="images/twitter.png"></a>
  
  </script>
  <a href="http://www.facebook.com/simplonve" target="_blank"><img src="images/facebook.png"></a>
</div>

<p>Created with ♥ on Ruby on Rails</p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SiteOfficielSimplonve</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="css/style.css">
  <meta name="viewport" content="width=device-width"> 
</head>
<body>
<ul class="navigationve">
	<li class="navigationve-link"><%= link_to 'Accueil', root_path %></li>
	<li class="navigationve-link"><%= link_to 'Blog', articles_path %></li>
	<li class="navigationve-link"><%= link_to 'Intervenants', intervenants_path %></li>
</ul>


<%= yield %>

</body>
<%= render "layouts/footer" %>
</html>